#!/usr/bin/env bash

# Generates eDR3int4 catalogs

# Get script path
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  GSDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$GSDIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
GSDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Locations
LOGS_LOC="$GSDIR/log/edr3int4"
DATA_LOC="$HOME/gaiadata"
DR_BASE="$DATA_LOC/eDR3"
DR_LOC="$DR_BASE/int4"
CATALOG_NAME="edr3int4"
INPUT="$DR_LOC/csv"
OUTPUT="$DR_LOC/out-rs"

# Definition file
CATDEF="$GSDIR/catalogs-edr3int4.json"

# Column names (see ColId)
COLS="sourceid,ra,dec,pllx,ra_err,dec_err,pllx_err,pmra,pmdec,radvel,gmag,bpmag,rpmag,ruwe,ref_epoch"

source catalogs-gen.sh
